# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ejemplo_03.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 358)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 0, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.e_n1 = QtWidgets.QLineEdit(self.centralwidget)
        self.e_n1.setGeometry(QtCore.QRect(270, 90, 231, 20))
        self.e_n1.setObjectName("e_n1")
        self.e_n2 = QtWidgets.QLineEdit(self.centralwidget)
        self.e_n2.setGeometry(QtCore.QRect(270, 130, 231, 20))
        self.e_n2.setObjectName("e_n2")
        self.b_aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.b_aceptar.setGeometry(QtCore.QRect(310, 160, 93, 28))
        self.b_aceptar.setObjectName("b_aceptar")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(7, 220, 521, 20))
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.l_opor = QtWidgets.QLabel(self.centralwidget)
        self.l_opor.setGeometry(QtCore.QRect(330, 240, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.l_opor.setFont(font)
        self.l_opor.setObjectName("l_opor")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LOGIN DEL SISTEMA"))
        self.label_2.setText(_translate("MainWindow", "INGRESAR USUARIO"))
        self.label_3.setText(_translate("MainWindow", "INGRESAR PASSWORD"))
        self.b_aceptar.setText(_translate("MainWindow", "ACEPTAR"))
        self.label_4.setText(_translate("MainWindow", "CANTIDAD DE OPORTUNIDADES"))
        self.l_opor.setText(_translate("MainWindow", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
