# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu(object):
    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.resize(524, 157)
        self.centralwidget = QtWidgets.QWidget(menu)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 0, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_personal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_personal.setGeometry(QtCore.QRect(110, 50, 131, 23))
        self.btn_personal.setObjectName("btn_personal")
        self.btn_alumno = QtWidgets.QPushButton(self.centralwidget)
        self.btn_alumno.setGeometry(QtCore.QRect(250, 50, 131, 23))
        self.btn_alumno.setObjectName("btn_alumno")
        self.btn_cerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cerrar.setGeometry(QtCore.QRect(180, 80, 131, 23))
        self.btn_cerrar.setObjectName("btn_cerrar")
        menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 21))
        self.menubar.setObjectName("menubar")
        menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menu)
        self.statusbar.setObjectName("statusbar")
        menu.setStatusBar(self.statusbar)

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)

    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("menu", "MainWindow"))
        self.label.setText(_translate("menu", "MENU PRINCIPAL"))
        self.btn_personal.setText(_translate("menu", "PERSONAL"))
        self.btn_alumno.setText(_translate("menu", "ALUMNO"))
        self.btn_cerrar.setText(_translate("menu", "CERRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu = QtWidgets.QMainWindow()
    ui = Ui_menu()
    ui.setupUi(menu)
    menu.show()
    sys.exit(app.exec_())
