# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventpersona.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_persona(object):
    def setupUi(self, persona):
        persona.setObjectName("persona")
        persona.resize(526, 585)
        self.centralwidget = QtWidgets.QWidget(persona)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 0, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_retornar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_retornar.setGeometry(QtCore.QRect(390, 500, 131, 23))
        self.btn_retornar.setObjectName("btn_retornar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_id = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_id.setGeometry(QtCore.QRect(190, 90, 211, 20))
        self.txt_id.setObjectName("txt_id")
        self.txt_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nombre.setGeometry(QtCore.QRect(190, 130, 211, 20))
        self.txt_nombre.setObjectName("txt_nombre")
        self.txt_edad = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_edad.setGeometry(QtCore.QRect(190, 180, 211, 20))
        self.txt_edad.setObjectName("txt_edad")
        self.btn_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_registrar.setGeometry(QtCore.QRect(210, 210, 131, 23))
        self.btn_registrar.setObjectName("btn_registrar")
        self.listar = QtWidgets.QTextBrowser(self.centralwidget)
        self.listar.setGeometry(QtCore.QRect(0, 240, 521, 251))
        self.listar.setObjectName("listar")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 510, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lbl_reg = QtWidgets.QLabel(self.centralwidget)
        self.lbl_reg.setGeometry(QtCore.QRect(220, 500, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_reg.setFont(font)
        self.lbl_reg.setObjectName("lbl_reg")
        persona.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(persona)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 526, 21))
        self.menubar.setObjectName("menubar")
        persona.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(persona)
        self.statusbar.setObjectName("statusbar")
        persona.setStatusBar(self.statusbar)

        self.retranslateUi(persona)
        QtCore.QMetaObject.connectSlotsByName(persona)

    def retranslateUi(self, persona):
        _translate = QtCore.QCoreApplication.translate
        persona.setWindowTitle(_translate("persona", "MainWindow"))
        self.label.setText(_translate("persona", "VENTANA PERSONA"))
        self.btn_retornar.setText(_translate("persona", "RETORNAR"))
        self.label_2.setText(_translate("persona", "INGRESAR ID PERSONA"))
        self.label_3.setText(_translate("persona", "INGRESAR NOMBRE"))
        self.label_4.setText(_translate("persona", "INGRESAR EDAD"))
        self.btn_registrar.setText(_translate("persona", "REGISTRAR"))
        self.label_5.setText(_translate("persona", "CANTIDAD DE REGISTROS"))
        self.lbl_reg.setText(_translate("persona", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    persona = QtWidgets.QMainWindow()
    ui = Ui_persona()
    ui.setupUi(persona)
    persona.show()
    sys.exit(app.exec_())
