# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventalumno.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_alumno(object):
    def setupUi(self, alumno):
        alumno.setObjectName("alumno")
        alumno.resize(522, 555)
        self.centralwidget = QtWidgets.QWidget(alumno)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 0, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_retornar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_retornar.setGeometry(QtCore.QRect(160, 290, 131, 23))
        self.btn_retornar.setObjectName("btn_retornar")
        alumno.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(alumno)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 522, 21))
        self.menubar.setObjectName("menubar")
        alumno.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(alumno)
        self.statusbar.setObjectName("statusbar")
        alumno.setStatusBar(self.statusbar)

        self.retranslateUi(alumno)
        QtCore.QMetaObject.connectSlotsByName(alumno)

    def retranslateUi(self, alumno):
        _translate = QtCore.QCoreApplication.translate
        alumno.setWindowTitle(_translate("alumno", "MainWindow"))
        self.label.setText(_translate("alumno", "VENTANA ALUMNO"))
        self.btn_retornar.setText(_translate("alumno", "RETORNAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    alumno = QtWidgets.QMainWindow()
    ui = Ui_alumno()
    ui.setupUi(alumno)
    alumno.show()
    sys.exit(app.exec_())
