# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(423, 206)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 0, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 141, 16))
        self.label_3.setObjectName("label_3")
        self.txt_n1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_n1.setGeometry(QtCore.QRect(170, 40, 113, 20))
        self.txt_n1.setObjectName("txt_n1")
        self.txt_n2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_n2.setGeometry(QtCore.QRect(170, 70, 113, 20))
        self.txt_n2.setObjectName("txt_n2")
        self.btn_aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_aceptar.setGeometry(QtCore.QRect(70, 120, 65, 20))
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.btn_cerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cerrar.setGeometry(QtCore.QRect(180, 120, 65, 20))
        self.btn_cerrar.setObjectName("btn_cerrar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 423, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LOGIN DEL SISTEMA"))
        self.label_2.setText(_translate("MainWindow", "INGRESAR USUARIO"))
        self.label_3.setText(_translate("MainWindow", "INGRESAR PASSWORD"))
        self.btn_aceptar.setText(_translate("MainWindow", "ACEPTAR"))
        self.btn_cerrar.setText(_translate("MainWindow", "CERRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
