# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vent_menu(object):
    def setupUi(self, vent_menu):
        vent_menu.setObjectName("vent_menu")
        vent_menu.resize(396, 251)
        self.centralwidget = QtWidgets.QWidget(vent_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 0, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_persona = QtWidgets.QPushButton(self.centralwidget)
        self.btn_persona.setGeometry(QtCore.QRect(110, 50, 121, 20))
        self.btn_persona.setObjectName("btn_persona")
        self.btn_cerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cerrar.setGeometry(QtCore.QRect(110, 140, 121, 20))
        self.btn_cerrar.setObjectName("btn_cerrar")
        vent_menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(vent_menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 396, 26))
        self.menubar.setObjectName("menubar")
        vent_menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(vent_menu)
        self.statusbar.setObjectName("statusbar")
        vent_menu.setStatusBar(self.statusbar)

        self.retranslateUi(vent_menu)
        QtCore.QMetaObject.connectSlotsByName(vent_menu)

    def retranslateUi(self, vent_menu):
        _translate = QtCore.QCoreApplication.translate
        vent_menu.setWindowTitle(_translate("vent_menu", "MainWindow"))
        self.label.setText(_translate("vent_menu", "MENU PRINCIPAL"))
        self.btn_persona.setText(_translate("vent_menu", "TABLA PERSONAL"))
        self.btn_cerrar.setText(_translate("vent_menu", "CERRAR VENTANA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vent_menu = QtWidgets.QMainWindow()
    ui = Ui_vent_menu()
    ui.setupUi(vent_menu)
    vent_menu.show()
    sys.exit(app.exec_())
