# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'persona.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vent_persona(object):
    def setupUi(self, vent_persona):
        vent_persona.setObjectName("vent_persona")
        vent_persona.resize(366, 255)
        self.centralwidget = QtWidgets.QWidget(vent_persona)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 141, 21))
        self.label_5.setObjectName("label_5")
        self.txt_n1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_n1.setGeometry(QtCore.QRect(150, 30, 113, 20))
        self.txt_n1.setObjectName("txt_n1")
        self.txt_n2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_n2.setGeometry(QtCore.QRect(150, 60, 113, 20))
        self.txt_n2.setObjectName("txt_n2")
        self.txt_n3 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_n3.setGeometry(QtCore.QRect(150, 90, 113, 20))
        self.txt_n3.setObjectName("txt_n3")
        self.lbl_regis = QtWidgets.QLabel(self.centralwidget)
        self.lbl_regis.setGeometry(QtCore.QRect(160, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_regis.setFont(font)
        self.lbl_regis.setObjectName("lbl_regis")
        self.btn_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_registrar.setGeometry(QtCore.QRect(54, 180, 81, 21))
        self.btn_registrar.setObjectName("btn_registrar")
        self.btn_cerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cerrar.setGeometry(QtCore.QRect(170, 180, 65, 21))
        self.btn_cerrar.setObjectName("btn_cerrar")
        vent_persona.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(vent_persona)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 366, 26))
        self.menubar.setObjectName("menubar")
        vent_persona.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(vent_persona)
        self.statusbar.setObjectName("statusbar")
        vent_persona.setStatusBar(self.statusbar)

        self.retranslateUi(vent_persona)
        QtCore.QMetaObject.connectSlotsByName(vent_persona)

    def retranslateUi(self, vent_persona):
        _translate = QtCore.QCoreApplication.translate
        vent_persona.setWindowTitle(_translate("vent_persona", "MainWindow"))
        self.label.setText(_translate("vent_persona", "TABLA PERSONA"))
        self.label_2.setText(_translate("vent_persona", "INGRESAR CODIGO"))
        self.label_3.setText(_translate("vent_persona", "INGRESAR NOMBRE"))
        self.label_4.setText(_translate("vent_persona", "INGRESAR EDAD"))
        self.label_5.setText(_translate("vent_persona", "POSICION DE REGISTRO"))
        self.lbl_regis.setText(_translate("vent_persona", "0"))
        self.btn_registrar.setText(_translate("vent_persona", "REGISTRAR"))
        self.btn_cerrar.setText(_translate("vent_persona", "CERRAR"))
        
        
