# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vent_tabla1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tabla1(object):
    def setupUi(self, tabla1):
        tabla1.setObjectName("tabla1")
        tabla1.resize(533, 395)
        self.centralwidget = QtWidgets.QWidget(tabla1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 0, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cerrar.setGeometry(QtCore.QRect(420, 110, 75, 23))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 160, 511, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 171, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 161, 16))
        self.label_4.setObjectName("label_4")
        self.txt_id = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_id.setGeometry(QtCore.QRect(190, 60, 171, 20))
        self.txt_id.setObjectName("txt_id")
        self.txt_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nombre.setGeometry(QtCore.QRect(190, 90, 171, 20))
        self.txt_nombre.setObjectName("txt_nombre")
        self.txt_apellido = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_apellido.setGeometry(QtCore.QRect(190, 120, 171, 20))
        self.txt_apellido.setObjectName("txt_apellido")
        self.registrar = QtWidgets.QPushButton(self.centralwidget)
        self.registrar.setGeometry(QtCore.QRect(420, 70, 75, 23))
        self.registrar.setObjectName("registrar")
        tabla1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(tabla1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 533, 22))
        self.menubar.setObjectName("menubar")
        tabla1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(tabla1)
        self.statusbar.setObjectName("statusbar")
        tabla1.setStatusBar(self.statusbar)

        self.retranslateUi(tabla1)
        QtCore.QMetaObject.connectSlotsByName(tabla1)

    def retranslateUi(self, tabla1):
        _translate = QtCore.QCoreApplication.translate
        tabla1.setWindowTitle(_translate("tabla1", "MainWindow"))
        self.label.setText(_translate("tabla1", "TABLA 01"))
        self.btn_cerrar.setText(_translate("tabla1", "CERRAR"))
        self.label_2.setText(_translate("tabla1", "INGRESAR ID_CLIENTE"))
        self.label_3.setText(_translate("tabla1", "INGRESAR NOMBRE CLIENTE"))
        self.label_4.setText(_translate("tabla1", "INGRESAR APELLIDO CLIENTE"))
        self.registrar.setText(_translate("tabla1", "REGISTRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabla1 = QtWidgets.QMainWindow()
    ui = Ui_tabla1()
    ui.setupUi(tabla1)
    tabla1.show()
    sys.exit(app.exec_())
