"""PASSWORD 

3 DEL NOMBRE SOLO UTIIZAMOS LAS TRES PRIMERAS LETRAS Y CREAMOS UNA PLANTILLA 

4 DE LAS TRES ULTIMAS LETRAS DE TU APELLIDO SACAMOS SU VALOR DE LA TABLA ASCII Y SUMAMOS CADA LETRA. 

5 EL PASSWORD ES LA COMBINACION DE AMBOS EL NOMBRE Y EL APELLIDO 

ANA                 !=! 

LOPEZ            PEZ=80+69+90=239 

                           !=!239 """


    
