# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eidan_calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Eidan(object):
    def setupUi(self, Eidan):
        Eidan.setObjectName("Eidan")
        Eidan.resize(535, 600)
        font = QtGui.QFont()
        font.setPointSize(16)
        Eidan.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Eidan)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 40, 131, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 100, 131, 31))
        self.label_2.setObjectName("label_2")
        self.val_a = QtWidgets.QLineEdit(self.centralwidget)
        self.val_a.setGeometry(QtCore.QRect(230, 40, 121, 31))
        self.val_a.setObjectName("val_a")
        self.val_b = QtWidgets.QLineEdit(self.centralwidget)
        self.val_b.setGeometry(QtCore.QRect(230, 100, 121, 31))
        self.val_b.setObjectName("val_b")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 150, 151, 31))
        self.label_3.setObjectName("label_3")
        self.resultado = QtWidgets.QLabel(self.centralwidget)
        self.resultado.setGeometry(QtCore.QRect(230, 150, 151, 31))
        self.resultado.setObjectName("resultado")
        self.btn_resta = QtWidgets.QPushButton(self.centralwidget)
        self.btn_resta.setGeometry(QtCore.QRect(270, 210, 181, 51))
        self.btn_resta.setObjectName("btn_resta")
        self.btn_divi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_divi.setGeometry(QtCore.QRect(40, 280, 181, 51))
        self.btn_divi.setObjectName("btn_divi")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(270, 280, 181, 51))
        self.btn_mult.setObjectName("btn_mult")
        self.btn_suma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_suma.setGeometry(QtCore.QRect(40, 210, 181, 51))
        self.btn_suma.setObjectName("btn_suma")
        self.btn_clean = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clean.setGeometry(QtCore.QRect(150, 360, 181, 51))
        self.btn_clean.setObjectName("btn_clean")
        self.box_msm_resultado = QtWidgets.QLabel(self.centralwidget)
        self.box_msm_resultado.setGeometry(QtCore.QRect(40, 450, 411, 31))
        self.box_msm_resultado.setStyleSheet("color: rgb(0, 170, 0);")
        self.box_msm_resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.box_msm_resultado.setObjectName("box_msm_resultado")
        Eidan.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Eidan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 535, 43))
        self.menubar.setObjectName("menubar")
        self.menuOperaciones = QtWidgets.QMenu(self.menubar)
        self.menuOperaciones.setObjectName("menuOperaciones")
        Eidan.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Eidan)
        self.statusbar.setObjectName("statusbar")
        Eidan.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuOperaciones.menuAction())

        self.retranslateUi(Eidan)
        QtCore.QMetaObject.connectSlotsByName(Eidan)

    def retranslateUi(self, Eidan):
        _translate = QtCore.QCoreApplication.translate
        Eidan.setWindowTitle(_translate("Eidan", "Calculadora"))
        self.label.setText(_translate("Eidan", "Valor 1:"))
        self.label_2.setText(_translate("Eidan", "Valor 2:"))
        self.label_3.setText(_translate("Eidan", "Resultado:"))
        self.resultado.setText(_translate("Eidan", "---"))
        self.btn_resta.setText(_translate("Eidan", "Restar"))
        self.btn_divi.setText(_translate("Eidan", "Dividir"))
        self.btn_mult.setText(_translate("Eidan", "Multiplicar"))
        self.btn_suma.setText(_translate("Eidan", "Sumar"))
        self.btn_clean.setText(_translate("Eidan", "Limpiar"))
        self.box_msm_resultado.setText(_translate("Eidan", ""))
        self.menuOperaciones.setTitle(_translate("Eidan", "Operaciones"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Eidan = QtWidgets.QMainWindow()
    ui = Ui_Eidan()
    ui.setupUi(Eidan)
    Eidan.show()
    sys.exit(app.exec_())
