# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LOGIN(object):
    def setupUi(self, LOGIN):
        LOGIN.setObjectName("LOGIN")
        LOGIN.resize(425, 262)
        self.centralwidget = QtWidgets.QWidget(LOGIN)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 30, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 110, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txt_n1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_n1.setGeometry(QtCore.QRect(240, 70, 113, 20))
        self.txt_n1.setObjectName("txt_n1")
        self.txt_n2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_n2.setGeometry(QtCore.QRect(240, 100, 113, 20))
        self.txt_n2.setObjectName("txt_n2")
        self.btn_aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_aceptar.setGeometry(QtCore.QRect(100, 150, 75, 23))
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.btn_cerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cerrar.setGeometry(QtCore.QRect(230, 150, 75, 23))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 70, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        LOGIN.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LOGIN)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 425, 21))
        self.menubar.setObjectName("menubar")
        LOGIN.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LOGIN)
        self.statusbar.setObjectName("statusbar")
        LOGIN.setStatusBar(self.statusbar)

        self.retranslateUi(LOGIN)
        QtCore.QMetaObject.connectSlotsByName(LOGIN)

    def retranslateUi(self, LOGIN):
        _translate = QtCore.QCoreApplication.translate
        LOGIN.setWindowTitle(_translate("LOGIN", "MainWindow"))
        self.label.setText(_translate("LOGIN", "LOGIN DEL SISTEMA"))
        self.label_3.setText(_translate("LOGIN", "INGRESAR PASSWORD"))
        self.btn_aceptar.setText(_translate("LOGIN", "ACEPTAR"))
        self.btn_cerrar.setText(_translate("LOGIN", "CERRAR"))
        self.label_4.setText(_translate("LOGIN", "INGRESAR USUARIO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LOGIN = QtWidgets.QMainWindow()
    ui = Ui_LOGIN()
    ui.setupUi(LOGIN)
    LOGIN.show()
    sys.exit(app.exec_())
