# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vent_menu(object):
    def setupUi(self, vent_menu):
        vent_menu.setObjectName("vent_menu")
        vent_menu.resize(439, 357)
        self.centralwidget = QtWidgets.QWidget(vent_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 30, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_clientes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clientes.setGeometry(QtCore.QRect(160, 70, 111, 23))
        self.btn_clientes.setObjectName("btn_clientes")
        self.btn_empleados = QtWidgets.QPushButton(self.centralwidget)
        self.btn_empleados.setGeometry(QtCore.QRect(160, 190, 111, 23))
        self.btn_empleados.setObjectName("btn_empleados")
        self.btn_clientesEmpresa = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clientesEmpresa.setGeometry(QtCore.QRect(160, 100, 111, 23))
        self.btn_clientesEmpresa.setObjectName("btn_clientesEmpresa")
        self.btn_detalleVenta = QtWidgets.QPushButton(self.centralwidget)
        self.btn_detalleVenta.setGeometry(QtCore.QRect(160, 130, 111, 23))
        self.btn_detalleVenta.setObjectName("btn_detalleVenta")
        self.btn_productos = QtWidgets.QPushButton(self.centralwidget)
        self.btn_productos.setGeometry(QtCore.QRect(160, 230, 111, 21))
        self.btn_productos.setObjectName("btn_productos")
        self.btn_cerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cerrar.setGeometry(QtCore.QRect(160, 260, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_cerrar.setFont(font)
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.btn_documentoVenta = QtWidgets.QPushButton(self.centralwidget)
        self.btn_documentoVenta.setGeometry(QtCore.QRect(150, 160, 131, 23))
        self.btn_documentoVenta.setObjectName("btn_documentoVenta")
        vent_menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(vent_menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 439, 21))
        self.menubar.setObjectName("menubar")
        vent_menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(vent_menu)
        self.statusbar.setObjectName("statusbar")
        vent_menu.setStatusBar(self.statusbar)

        self.retranslateUi(vent_menu)
        QtCore.QMetaObject.connectSlotsByName(vent_menu)

    def retranslateUi(self, vent_menu):
        _translate = QtCore.QCoreApplication.translate
        vent_menu.setWindowTitle(_translate("vent_menu", "MainWindow"))
        self.label.setText(_translate("vent_menu", "MENU PRINCIPAL"))
        self.btn_clientes.setText(_translate("vent_menu", "CLIENTES"))
        self.btn_empleados.setText(_translate("vent_menu", "EMPLEADOS"))
        self.btn_clientesEmpresa.setText(_translate("vent_menu", "CLIENTE EMPRESA"))
        self.btn_detalleVenta.setText(_translate("vent_menu", "DETALLE DE VENTA"))
        self.btn_productos.setText(_translate("vent_menu", "PRODUCTOS"))
        self.btn_cerrar.setText(_translate("vent_menu", "CERRAR VENTANA"))
        self.btn_documentoVenta.setText(_translate("vent_menu", "DOCUMENTO DE VENTAS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vent_menu = QtWidgets.QMainWindow()
    ui = Ui_vent_menu()
    ui.setupUi(vent_menu)
    vent_menu.show()
    sys.exit(app.exec_())
